#!/bin/bash
echo "Running asyncRead..."
ls /dev/ | grep ttyACM
sudo java -cp .:ltkjava-1.0.0.6.jar:mercuryapi.jar asyncRead tmr:///dev/ttyACM0 --ant 2 &
#sudo killall gpsd
#sudo gpsd /dev/ttyAMA0 -F /var/run/gpsd.sock
#cgps -s &
#sleep 1
sudo cat /dev/ttyAMA0 | sudo grep GPRMC > /mnt/usb/gps.log

